fix: apl cmd variables (CORE-1816)
voiceflow/alexa-client pull request #92
Opened 2020-10-07 19:57 UTC by nidhigaday

2020-10-16 17:54 UTC, vyancharuk approved these changes

2020-10-23 16:47 UTC, leartgjoni-voiceflow requested changes

2020-10-23 16:47 UTC, leartgjoni-voiceflow commented on lib/services/voiceflow/handlers/display/index.ts
> +        commands = JSON.parse(regexVariables(node.apl_commands, variables)) as Command[];
`regexVariables` needs to be added in the `utilsObj` to follow the DI pattern

2020-10-23 17:50 UTC, leartgjoni-voiceflow approved these changes

2020-10-23 17:57 UTC, merged

2020-10-23 18:02 UTC, vf-service-account commented
:tada: This PR is included in version 1.17.4 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/alexa-client/releases/tag/v1.17.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: